---
- hosts: all

  become: true

  vars_prompt:
    - name: "Database"
      prompt: "Enter Database name"
      private: no

    - name: "Table"
      prompt: "Enter Table name"
      private: no

  tasks:

    - name: Actualizando la cache de apt
      apt: update_cache=yes
  
    - include: sqlite.yml
    - include: munin.yml
